deck:
  spyglass:
    size_limit: 500000000 # 500MB
    lenses:
      - lens:
          name: metadata
        required_files:
        - started.json|finished.json
        optional_files:
        - podinfo.json
      - lens:
          name: buildlog
        required_files:
          - build-log.txt
      - lens:
          name: podinfo
        required_files:
          - podinfo.json

plank:
  job_url_template: 'http://prow.kubecoins.com/view/s3/kubecoins-prow-logs/{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if .Spec.Refs}}{{if ne .Spec.Refs.Org ""}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  job_url_prefix_config:
    '*': http://prow.kubecoins.com/view/
  report_templates:
    '*': '[Full PR test history](http://prow.kubecoins.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/issues?q=is:issue+is:open) when you hit one in your PR.'
  max_concurrency: 100 # Limit of concurrent ProwJobs. Need to be adjusted depending of the cluster size.
  pod_pending_timeout: 60m
  default_decoration_configs:
    '*':
      timeout: 24h # Up to 12 hours for driverkit builder jobs
      grace_period: 10m
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20210108-eac8059329"
        initupload: "gcr.io/k8s-prow/initupload:v20210108-eac8059329"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20210108-eac8059329"
        sidecar: "gcr.io/k8s-prow/sidecar:v20210108-eac8059329"
      gcs_configuration:
        bucket: s3://kubecoins-prow-logs
        path_strategy: explicit
      s3_credentials_secret: "s3-credentials" #secret in use with IAM creds for sidecar pod log upload

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 24h
  terminated_pod_ttl: 2h

branch-protection:
  enforce_admins: true # rules apply to admins too!
  restrictions: # restrict who can push
    teams: ["maintainers", "machine_users"]
  required_pull_request_reviews:
    dismiss_stale_reviews: true # automat dismiss old reviews
    dismissal_restrictions: # allow review dismissals
      teams:
        - maintainers
        - machine_users
    require_code_owner_reviews: true # require a code owner approval
    required_approving_review_count: 1 # number of approvals
  required_status_checks:
    strict: false # we don't want to block any PR if it's not up to date, we have the rebase merge strategy and needs-rebase plugin
  orgs:
    kubecoins:
      protect: true
      required_status_checks:
        contexts:
          - dco
      exclude:
        - "^dependabot/" # don't protect branches created by dependabot
      repos:
        test-infra:
          branches:
            main:
              protect: true

log_level: debug
pod_namespace: test-pods
prowjob_namespace: default
in_repo_config:
  enabled:
    "*": true

tide:
  context_options:
    skip-unknown-contexts: true
    from-branch-protection: true
  merge_method:
    kubecoins/test-infra: rebase
  queries:
    - repos:
        - kubecoins/test-infra
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
