# Plugin configuration
---
triggers:
- repos:
  - kubecoins/test-infra
  join_org_url: "https://github.com/kubecoins/test-infra/blob/main/README.md"
  only_org_members: true

approve:
- repos:
  - kubecoins/test-infra
  lgtm_acts_as_approve: true
  require_self_approval: true

config_updater:
  maps:
    config/config.yaml:
      name: config
    config/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config
      gzip: true

label:
  additional_labels:
    - kind/infra

lgtm:
- repos:
  - kubecoins/test-infra
  review_acts_as_lgtm: true
  store_tree_hash: true

blunderbuss:
  max_request_count: 2
  use_status_availability: true

size:
  s: 10
  m: 30
  l: 90
  xl: 270
  xxl: 520

plugins:
  kubecoins/test-infra:
    - approve # Allow OWNERS to /approve
    - assign # Allow /assign and /cc
    - blunderbuss  # Auto-assign people
    - lgtm # Allow /lgtm
    - help  # Support /help and /good-first-issue
    - hold  # Support /hold to delay merge
    - skip
    - size # Auto-label size of PR
    - trigger  # Allow people to configure CI jobs to /test
    - welcome
    - owners-label
    - label
    - verify-owners # Validates OWNERS file changes in PRs.
    - wip  # Auto-hold PRs with WIP in title
    - release-note

external_plugins:
  kubecoins:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request
